(() => {
  "use strict";
  const cfg = window.VM_CONFIG || {};
  const state = {books:[],filtered:[],pins:new Set(JSON.parse(localStorage.getItem("vm-pins")||"[]")),page:1,pageSize:12,view:localStorage.getItem("vm-view")||"grid",lang:localStorage.getItem("vm-lang")||"lv",selected:{topic:new Set(),language:new Set()},yearFrom:"",yearTo:"",routeBook:null};
  const $=s=>document.querySelector(s);
  const tr={
    lv:{books:"Grāmatas",about:"Par bibliotēku",search:"Meklēt",searchPlaceholder:"Meklēt pēc nosaukuma, autora, tēmas, atslēgvārda…",pinNote:"Piespraustās grāmatas tiek rādītas vispirms.",clearPins:"Noņemt piespraustās grāmatas",sortBy:"Kārtot pēc:",perPage:"Grāmatas lapā:",aboutText:"",author:"Autors",year:"Gads",language:"Valoda",topic:"Tēma",comments:"Piezīmes",noResults:"Neviena grāmata neatbilst izvēlētajiem filtriem.",notFound:"Grāmata ar šo saiti netika atrasta.",loading:"Ielādē katalogu…",results:n=>`${n} grāmatas`,prev:"Iepriekšējā",next:"Nākamā",all:"Visi",selected:n=>`${n} izvēlēti`,filterTopic:"Tēma",filterLanguage:"Valoda",yearFrom:"No",yearTo:"Līdz",sortNewest:"Jaunākie vispirms",sortOldest:"Vecākie vispirms",sortTitle:"Nosaukums A–Z",sortAuthor:"Autors A–Z",pin:"Piespraust",unpin:"Atspraust",resetFilters:"Atiestatīt visus filtrus",removeFilter:"Noņemt filtru",back:"Atpakaļ uz visām grāmatām",showFilters:"Rādīt filtrus",hideFilters:"Paslēpt filtrus",bookDetails:"Grāmatas informācija"},
    en:{books:"Books",about:"About the library",search:"Search",searchPlaceholder:"Search by title, author, topic or keyword…",pinNote:"Pinned books are shown first.",clearPins:"Remove pinned books",sortBy:"Sort by:",perPage:"Books per page:",aboutText:"",author:"Author",year:"Year",language:"Language",topic:"Topic",comments:"Notes",noResults:"No books match the selected filters.",notFound:"No book was found for this link.",loading:"Loading catalogue…",results:n=>`${n} books`,prev:"Previous",next:"Next",all:"All",selected:n=>`${n} selected`,filterTopic:"Topic",filterLanguage:"Language",yearFrom:"From",yearTo:"To",sortNewest:"Newest first",sortOldest:"Oldest first",sortTitle:"Title A–Z",sortAuthor:"Author A–Z",pin:"Pin",unpin:"Unpin",resetFilters:"Reset all filters",removeFilter:"Remove filter",back:"Back to all books",showFilters:"Show filters",hideFilters:"Hide filters",bookDetails:"Book details"}
  };
  const t=k=>tr[state.lang][k];
  const topicLabels={
    "Språklæring":{lv:"Valodu mācīšanās",en:"Language Studying"},
    "Undervisning":{lv:"Valodu mācīšanas",en:"Language Teaching"},
    "Språktesting":{lv:"Valodu līmeņa pārbaudīšanas",en:"Language Testing"},
    "Kombinert":{lv:"Kombinēts",en:"Multiple"},
    "Annet":{lv:"Cits",en:"Other"}
  };
  const filterLabel=(key,value)=>{
    if(key==="topic"&&topicLabels[value])return topicLabels[value][state.lang];
    if(key==="language"&&String(value).trim().toLowerCase()==="other"&&state.lang==="lv")return "Cita valoda";
    return String(value);
  };
  const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const pinSvg=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.2 3.5h7.6l-1 5.1 3.2 3.2v1.7H6v-1.7l3.2-3.2-1-5.1Z"/><path d="M12 13.5V21"/></svg>`;
  const placeholder=title=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 340"><rect width="240" height="340" fill="#f3ede8"/><path d="M22 25h196v290H22z" fill="none" stroke="#fa4b16" stroke-width="4"/><text x="120" y="145" text-anchor="middle" font-family="sans-serif" font-size="17" fill="#444">VALODU MĀJA</text><text x="120" y="180" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#777">${esc(title).slice(0,24)}</text></svg>`)}`;
  const slugify=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-|-$/g,"");
  const copyNumber=b=>String(b.copyNumber||(String(b.copies||"").match(/\d+/)||["1"])[0]);
  const bookSlug=b=>`${b.year||"unknown"}-${copyNumber(b)}-${slugify(b.title)}`;

  async function load(){
    $("#status").textContent=t("loading");
    try{if(!cfg.apiUrl)throw new Error("sample");const res=await fetch(`${cfg.apiUrl}${cfg.apiUrl.includes("?")?"&":"?"}action=books`);if(!res.ok)throw new Error(`API ${res.status}`);const json=await res.json();if(!json.ok)throw new Error(json.error||"API error");state.books=json.books;}
    catch(err){state.books=window.VM_SAMPLE_BOOKS||[];if(err.message!=="sample")console.warn("Using sample data:",err);}
    buildFilters();applyLanguage();handleHash();
  }
  function sortedValues(key){const last=key==="language"?"other":"annet";return [...new Set(state.books.map(b=>b[key]).filter(Boolean))].sort((a,b)=>{const al=String(a).toLowerCase()===last,bl=String(b).toLowerCase()===last;if(al!==bl)return al?1:-1;return String(a).localeCompare(String(b),"lv",{numeric:true})});}
  function multiFilter(key,label){const values=sortedValues(key),selected=state.selected[key];return `<details class="multi-filter filter" data-key="${key}"><summary><span><small>${esc(label)}</small><strong>${selected.size?t("selected")(selected.size):t("all")}</strong></span><span aria-hidden="true">⌄</span></summary><div class="filter-menu">${values.map(v=>`<label><input type="checkbox" value="${esc(v)}" ${selected.has(String(v))?"checked":""}> <span>${esc(filterLabel(key,v))}</span></label>`).join("")}</div></details>`;}
  function buildFilters(){
    const years=[...new Set(state.books.map(b=>Number(b.year)).filter(Number.isFinite))].sort((a,b)=>a-b);
    const minYear=years[0]||1000,maxYear=years[years.length-1]||new Date().getFullYear();
    const fromValue=state.yearFrom||minYear,toValue=state.yearTo||maxYear;
    $("#filters").innerHTML=multiFilter("topic",t("filterTopic"))+multiFilter("language",t("filterLanguage"))+`<div class="year-slider filter"><div class="year-slider-title">${t("year")}</div><div class="year-values"><label><span>${t("yearFrom")}</span><input id="yearFrom" type="number" inputmode="numeric" min="${minYear}" max="${maxYear}" value="${fromValue}" aria-label="${t("yearFrom")}"></label><label><span>${t("yearTo")}</span><input id="yearTo" type="number" inputmode="numeric" min="${minYear}" max="${maxYear}" value="${toValue}" aria-label="${t("yearTo")}"></label></div><div class="dual-range"><div class="range-track"></div><div id="rangeFill" class="range-fill"></div><input id="yearFromRange" type="range" min="${minYear}" max="${maxYear}" value="${fromValue}" aria-label="${t("yearFrom")}"><input id="yearToRange" type="range" min="${minYear}" max="${maxYear}" value="${toValue}" aria-label="${t("yearTo")}"></div></div>`;
    document.querySelectorAll(".multi-filter input").forEach(input=>input.onchange=()=>{const details=input.closest("details"),key=details.dataset.key;input.checked?state.selected[key].add(input.value):state.selected[key].delete(input.value);details.querySelector("summary strong").textContent=state.selected[key].size?t("selected")(state.selected[key].size):t("all");state.page=1;apply();});
    const paintRange=()=>{const from=+$("#yearFromRange").value,to=+$("#yearToRange").value,span=maxYear-minYear||1;$("#rangeFill").style.left=`${(from-minYear)/span*100}%`;$("#rangeFill").style.right=`${100-(to-minYear)/span*100}%`};
    const commitYears=(from,to)=>{from=Math.max(minYear,Math.min(+from||minYear,maxYear));to=Math.max(minYear,Math.min(+to||maxYear,maxYear));if(from>to)[from,to]=[to,from];state.yearFrom=String(from);state.yearTo=String(to);$("#yearFrom").value=from;$("#yearTo").value=to;$("#yearFromRange").value=from;$("#yearToRange").value=to;paintRange();state.page=1;apply()};
    $("#yearFromRange").oninput=e=>commitYears(Math.min(+e.target.value,+$("#yearToRange").value),$("#yearToRange").value);
    $("#yearToRange").oninput=e=>commitYears($("#yearFromRange").value,Math.max(+e.target.value,+$("#yearFromRange").value));
    $("#yearFrom").onchange=()=>commitYears($("#yearFrom").value,$("#yearTo").value);$("#yearTo").onchange=()=>commitYears($("#yearFrom").value,$("#yearTo").value);paintRange();
  }
  function apply(){
    state.routeBook=null;const q=$("#query").value.trim().toLocaleLowerCase("lv");
    state.filtered=state.books.filter(b=>(!q||Object.values(b).join(" ").toLocaleLowerCase("lv").includes(q))&&(!state.selected.topic.size||state.selected.topic.has(String(b.topic)))&&(!state.selected.language.size||state.selected.language.has(String(b.language)))&&(!state.yearFrom||+b.year>=+state.yearFrom)&&(!state.yearTo||+b.year<=+state.yearTo));
    const sort=$("#sort").value;state.filtered.sort((a,b)=>{const pinned=Number(state.pins.has(b.id))-Number(state.pins.has(a.id));if(pinned)return pinned;if(sort==="newest")return(+b.year||0)-(+a.year||0);if(sort==="oldest")return(+a.year||0)-(+b.year||0);return String(a[sort]||a.title).localeCompare(String(b[sort]||b.title),"lv")});renderFilters();render();
  }
  function renderFilters(){
    const tags=[];["topic","language"].forEach(key=>state.selected[key].forEach(v=>{const label=filterLabel(key,v);tags.push(`<button class="filter-chip" data-key="${key}" data-value="${esc(v)}" aria-label="${t("removeFilter")}: ${esc(label)}">${esc(label)} ×</button>`)}));if(state.yearFrom)tags.push(`<button class="filter-chip" data-key="yearFrom">${t("yearFrom")}: ${state.yearFrom} ×</button>`);if(state.yearTo)tags.push(`<button class="filter-chip" data-key="yearTo">${t("yearTo")}: ${state.yearTo} ×</button>`);
    $("#activeFilters").innerHTML=tags.join("");$("#resetFilters").hidden=!tags.length&&!$("#query").value;$("#clearPins").hidden=!state.pins.size;
    document.querySelectorAll(".filter-chip").forEach(btn=>btn.onclick=()=>{const key=btn.dataset.key;if(key==="yearFrom"||key==="yearTo")state[key]="";else state.selected[key].delete(btn.dataset.value);state.page=1;buildFilters();apply()});
  }
  function render(){
    const books=state.routeBook?[state.routeBook]:state.filtered;$("#status").textContent=state.routeBook?"":t("results")(books.length);const pages=Math.max(1,Math.ceil(books.length/state.pageSize));state.page=Math.min(state.page,pages);const rows=state.routeBook?books:books.slice((state.page-1)*state.pageSize,state.page*state.pageSize);
    document.body.classList.toggle("book-detail-mode",!!state.routeBook);
    $("#gridView").classList.toggle("active",state.view==="grid");$("#listView").classList.toggle("active",state.view==="list");
    if(!rows.length){$("#results").innerHTML=`<div class="empty">${location.hash&&!['','#catalog','#about'].includes(location.hash)?t("notFound"):t("noResults")}</div>`;$("#pagination").innerHTML="";return;}
    $("#results").innerHTML=state.routeBook?detailPage(state.routeBook):(state.view==="grid"?`<div class="cards">${rows.map(card).join("")}</div>`:table(rows));
    document.querySelectorAll(".cover").forEach(img=>img.onerror=()=>{img.onerror=null;img.src=placeholder(img.dataset.title)});document.querySelectorAll(".pin").forEach(btn=>btn.onclick=()=>togglePin(btn.dataset.id));pagination(state.routeBook?1:pages);
  }
  function pinButton(b){return `<button class="pin ${state.pins.has(b.id)?"active":""}" data-id="${esc(b.id)}" aria-label="${state.pins.has(b.id)?t("unpin"):t("pin")} ${esc(b.title)}" aria-pressed="${state.pins.has(b.id)}">${pinSvg}</button>`;}
  function titleLink(b){return `<a class="book-link" href="#${esc(bookSlug(b))}">${esc(b.title)}</a>`;}
  function metadata(b,includeComments=false){const fields=[["language",b.language],["topic",b.topic],["year",b.year]];if(includeComments)fields.push(["comments",b.comments]);return fields.filter(([,v])=>v!==""&&v!=null).map(([k,v])=>`<div><dt>${t(k)}:</dt><dd>${esc(v)}</dd></div>`).join("");}
  function card(b){const cover=b.cover||placeholder(b.title);return `<article class="book-card">${pinButton(b)}<a class="cover-link" href="#${esc(bookSlug(b))}" aria-label="${esc(b.title)}"><img class="cover" src="${esc(cover)}" data-title="${esc(b.title)}" alt="${esc(b.title)} vāks" loading="lazy"></a><div class="card-copy"><h2>${titleLink(b)}</h2>${b.author?`<p class="author">${esc(b.author)}</p>`:""}${b.level?`<span class="level tag">${esc(b.level)}</span>`:""}<dl>${metadata(b)}</dl></div></article>`;}
  function detailPage(b){const cover=b.cover||placeholder(b.title);return `<a class="back-link" href="./">← ${t("back")}</a><article class="book-detail"><div class="detail-cover"><img class="cover" src="${esc(cover)}" data-title="${esc(b.title)}" alt="${esc(b.title)} vāks"></div><div class="detail-content"><p class="detail-eyebrow">${t("bookDetails")}</p><h1>${esc(b.title)}</h1>${b.author?`<p class="detail-author">${esc(b.author)}</p>`:""}<dl class="detail-meta">${metadata(b,true)}</dl>${pinButton(b)}</div></article>`;}
  function table(rows){return `<div style="overflow:auto"><table class="list-table"><thead><tr><th>${t("books")}</th><th>${t("author")}</th><th>${t("year")}</th><th>${t("topic")}</th><th>${t("language")}</th><th></th></tr></thead><tbody>${rows.map(b=>`<tr><td><div class="list-title"><a class="cover-link" href="#${esc(bookSlug(b))}"><img class="cover" src="${esc(b.cover||placeholder(b.title))}" data-title="${esc(b.title)}" alt=""></a><span>${titleLink(b)}</span></div></td><td>${esc(b.author||"")}</td><td>${esc(b.year||"")}</td><td>${esc(b.topic||"")}</td><td>${esc(b.language||"")}</td><td>${pinButton(b)}</td></tr>`).join("")}</tbody></table></div>`;}
  function pagination(pages){const nav=$("#pagination");if(pages<=1){nav.innerHTML="";return;}let html=`<button data-page="${state.page-1}" ${state.page===1?"disabled":""}>‹ ${t("prev")}</button>`;for(let p=1;p<=pages;p++)if(p===1||p===pages||Math.abs(p-state.page)<=1)html+=`<button data-page="${p}" class="${p===state.page?"active":""}">${p}</button>`;else if(p===2||p===pages-1)html+=`<span>…</span>`;html+=`<button data-page="${state.page+1}" ${state.page===pages?"disabled":""}>${t("next")} ›</button>`;nav.innerHTML=html;nav.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;render();$("#catalog").scrollIntoView()});}
  function resetFilters(){state.selected.topic.clear();state.selected.language.clear();state.yearFrom="";state.yearTo="";state.page=1;$("#query").value="";if(location.hash)history.pushState(null,"",location.pathname+location.search);buildFilters();apply();}
  function togglePin(id){state.pins.has(id)?state.pins.delete(id):state.pins.add(id);localStorage.setItem("vm-pins",JSON.stringify([...state.pins]));state.routeBook?render():apply();renderFilters();}
  function updateNavigation(){const aboutActive=location.hash==="#about";$("#booksNav").classList.toggle("active",!aboutActive);$("#aboutNav").classList.toggle("active",aboutActive);$("#booksNav").setAttribute("aria-current",aboutActive?"false":"page");$("#aboutNav").setAttribute("aria-current",aboutActive?"page":"false");}
  function handleHash(){const hash=decodeURIComponent(location.hash.slice(1));if(hash==="catalog")history.replaceState(null,"",location.pathname+location.search);updateNavigation();if(!hash||hash==="catalog"||hash==="about"){state.routeBook=null;apply();return;}state.routeBook=state.books.find(b=>bookSlug(b)===hash)||null;state.filtered=state.routeBook?[state.routeBook]:[];renderFilters();render();}
  function setView(v){state.view=v;localStorage.setItem("vm-view",v);render();}
  function applyLanguage(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));$("#langToggle").textContent=state.lang==="lv"?"LV / EN":"EN / LV";$("#query").placeholder=t("searchPlaceholder");const sort=$("#sort"),value=sort.value;sort.innerHTML=`<option value="newest">${t("sortNewest")}</option><option value="oldest">${t("sortOldest")}</option><option value="title">${t("sortTitle")}</option><option value="author">${t("sortAuthor")}</option>`;sort.value=value;buildFilters();$(".pin-note-icon").innerHTML=pinSvg;state.routeBook?render():apply();}
  $("#searchForm").onsubmit=e=>{e.preventDefault();state.page=1;if(location.hash&&!['','#catalog'].includes(location.hash))history.pushState(null,"","#catalog");apply();};$("#query").oninput=()=>{state.page=1;if(location.hash&&!['','#catalog'].includes(location.hash))history.replaceState(null,"","#catalog");apply();};$("#sort").onchange=apply;$("#pageSize").value="12";$("#pageSize").onchange=e=>{state.pageSize=Number(e.target.value);state.page=1;render();};$("#gridView").onclick=()=>setView("grid");$("#listView").onclick=()=>setView("list");$("#clearPins").onclick=()=>{state.pins.clear();localStorage.removeItem("vm-pins");state.routeBook?render():apply();renderFilters();};$("#resetFilters").onclick=resetFilters;
  $("#filtersToggle").onclick=()=>{const open=$("#filters").classList.toggle("mobile-open");$("#filtersToggle").setAttribute("aria-expanded",open);$("#filtersToggle").textContent=t(open?"hideFilters":"showFilters");};
  // Catalogue actions use the clean base URL rather than the legacy #catalog hash.
  $("#searchForm").onsubmit=e=>{e.preventDefault();state.page=1;if(location.hash)history.pushState(null,"",location.pathname+location.search);apply();};
  $("#query").oninput=()=>{state.page=1;if(location.hash)history.replaceState(null,"",location.pathname+location.search);apply();};
  $("#themeToggle").onclick=()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("vm-theme",next);};document.documentElement.dataset.theme=localStorage.getItem("vm-theme")||"light";
  let font=Number(localStorage.getItem("vm-font")||16);const setFont=n=>{font=Math.max(14,Math.min(20,n));document.documentElement.style.setProperty("--base",`${font}px`);localStorage.setItem("vm-font",font);};setFont(font);$("#fontDown").onclick=()=>setFont(font-1);$("#fontUp").onclick=()=>setFont(font+1);$("#langToggle").onclick=()=>{state.lang=state.lang==="lv"?"en":"lv";localStorage.setItem("vm-lang",state.lang);applyLanguage();};window.addEventListener("hashchange",handleHash);load();
})();
